title: NameGen
description: A C++ library designed to generate random names based on customizable patterns.
author: Enrico Fraccaroli
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
social:
  email: enrico.fraccaroli@univr.it
